# Generated by Django 3.1.5 on 2021-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('aventura', 'Aventura'), ('fps', 'Fps'), ('horror', 'Horror'), ('infatil', 'Infatil')], max_length=10)),
            ],
        ),
    ]
