# Generated by Django 3.1.5 on 2021-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
