# Generated by Django 3.1.5 on 2021-06-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_juego_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='category',
            field=models.CharField(choices=[('aventura', 'Aventura'), ('fps', 'Fps'), ('horror', 'Horror'), ('infantil', 'Infatil'), ('deportes', 'deportes')], max_length=10),
        ),
    ]
